# Generated by Django 5.0.7 on 2025-03-30 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(default='asdassdas.jpg', upload_to='movies/events/'),
            preserve_default=False,
        ),
    ]
