# Generated by Django 5.0.7 on 2025-04-03 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='booked',
            field=models.BooleanField(default=False),
        ),
    ]
